<?php

declare(strict_types=1);

namespace Framework\API\UseCases\Errors;

use ErrorException;
use Framework\API\UseCases\UseCaseErrorInterface;

/**
 * Represents an error that got generated by use case business logic.
 */
final class BusinessLogicError implements UseCaseErrorInterface
{
    /**
     * @param array<string> $errorMessages An indexed array of error message strings.
     *
     * @throws ErrorException when the given array is not an indexed array.
     */
    public function __construct(
        private readonly array $errorMessages,
    ) {
        if (!array_is_list($errorMessages)) {
            throw new ErrorException(
                'A "business logic" error may only contain an indexed array of error messages.'
            );
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function getFormatted(): array
    {
        return [
            'error' => [
                'type' => 'business-logic',
                'messages' => $this->errorMessages,
            ],
        ];
    }
}
